name: ${project.name}
description: "${project.description}"
main: com.renatusnetwork.glyphs.Glyphs
version: ${project.version}
author: [xxBen]
softdepend:
  - LuckPerms
commands:
  tags:
    aliases: [glyphs]
    description: Glyphs Tags Command
  glyphs:
    description: Glyphs Main Command